version: '3.8'

services:
  app:
    build: .
    ports:
      - "8080:8080"
    environment:
      - DB_URL=jdbc:postgresql://db:5432/budget_journal
      - DB_USER=postgres
      - DB_PASSWORD=postgres
      - DB_SCHEMA=budget_journal
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - ./logs:/usr/local/tomcat/logs

  db:
    image: postgres:15
    environment:
      - POSTGRES_DB=budget_journal
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
    command: >
      bash -c "
        echo 'Waiting for PostgreSQL to start...' &&
        while ! pg_isready -U postgres; do
          sleep 1
        done &&
        echo 'PostgreSQL started' &&
        psql -U postgres -d budget_journal -f /docker-entrypoint-initdb.d/init.sql &&
        postgres
      "

volumes:
  postgres_data: 